name: "Build & run tests"
on:
  - push
jobs:
  test:
    name: "Build & test"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
          architecture: 'x64'
      - name: Make mvnw executable
        run: chmod +x ${{ github.workspace }}/mvnw
        shell: bash
      - name: Run tests
        run: ${{ github.workspace }}/mvnw surefire-report:report
        shell: bash
      - name: Upload submitted tests report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: tests
          path: ${{ github.workspace }}/target/site/**
          if-no-files-found: ignore
